### ISSUE TITLE
doesnt round trip even 10 places

### ISSUE THREAD

**Issue by jeacott1** [andrew/base62.js#25]
```    
var Base62=require('base62');
var maxv= Base62.decode("ZZZZZZZZZZ");
var mmaxv = Base62.encode(maxv);
console.log("maxv=" +maxv+" mmaxv="+mmaxv);


>   maxv=839299365868340200 mmaxv=10000000000
```

**Comment by kchapelier** [comment]
This is due to the numbers being represented in JavaScript as IEEE 754 double-precision binary floating-point ([wiki](https://en.wikipedia.org/wiki/Double-precision_floating-point_format)) thus being only able to precisely represent integers up to 53 bits (the value of Number.MAX_SAFE_INTEGER, or Math.pow(2, 53) - 1).

The only way to bypass that would be to use custom number representation such as the `bignum` and `big-integer` modules. Some other base64 modules (`b64`) are doing just that, but it comes at a cost.
